version: '3.9'

services:
  postgres:
    image: postgres:13.8
    environment:
      POSTGRES_DB: tarask
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres/:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - local-tarask

  postgres-keycloak:
    image: postgres:13.8
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - ./postgresKeycloak/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - local-tarask

  keycloak:
    depends_on:
      - postgres-keycloak
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    image: jboss/keycloak:13.0.0
    ports:
      - "28080:8080"
    networks:
      - local-tarask

  #back:
  #  depends_on:
  #    - keycloak
  #  container_name: back_tarask
  #  image: tarask-event-back
  #  ports:
  #    - "8079:8080"
  #  networks:
  #    - local-tarask

networks:
  local-tarask:
